// WordSpark A2 Seed Data — 150 words, 5 topics
const W=(t,...d)=>d.map(r=>({word:r[0],ipa:r[1],pos:r[2],vi:r[3],en:r[4],ex_en:r[5],ex_vi:r[6],topic:t,level:'A2',lang:'en'}));
export const WORDS_A2 = [
  // 11. Emotions & Feelings
  ...W('Emotions & Feelings',
  ['happy','/ˈhæp.i/','adj','hạnh phúc','feeling joy','The children are happy.','Bọn trẻ rất hạnh phúc.'],
  ['sad','/sæd/','adj','buồn','feeling unhappy','She looks sad today.','Hôm nay cô ấy trông buồn.'],
  ['angry','/ˈæŋ.ɡri/','adj','tức giận','feeling mad','He is angry at me.','Anh ấy tức giận với tôi.'],
  ['afraid','/əˈfreɪd/','adj','sợ hãi','feeling fear','I am afraid of dogs.','Tôi sợ chó.'],
  ['excited','/ɪkˈsaɪ.t̬ɪd/','adj','hào hứng','very enthusiastic','We are excited about the trip.','Chúng tôi hào hứng về chuyến đi.'],
  ['bored','/bɔːrd/','adj','chán','not interested','I feel bored at home.','Tôi thấy chán ở nhà.'],
  ['surprised','/sɚˈpraɪzd/','adj','ngạc nhiên','feeling amazed','I was surprised by the gift.','Tôi ngạc nhiên vì món quà.'],
  ['worried','/ˈwɜːr.id/','adj','lo lắng','feeling anxious','She is worried about the exam.','Cô ấy lo lắng về kỳ thi.'],
  ['proud','/praʊd/','adj','tự hào','feeling satisfaction','I am proud of you!','Tôi tự hào về bạn!'],
  ['lonely','/ˈloʊn.li/','adj','cô đơn','feeling alone','He feels lonely sometimes.','Đôi khi anh ấy cảm thấy cô đơn.'],
  ['nervous','/ˈnɜːr.vəs/','adj','hồi hộp','feeling tense','I am nervous before exams.','Tôi hồi hộp trước kỳ thi.'],
  ['jealous','/ˈdʒel.əs/','adj','ghen tị','envious feeling','Do not be jealous.','Đừng ghen tị.'],
  ['comfortable','/ˈkʌmf.tɚ.bəl/','adj','thoải mái','feeling relaxed','This chair is comfortable.','Ghế này thoải mái.'],
  ['disappointed','/ˌdɪs.əˈpɔɪn.t̬ɪd/','adj','thất vọng','let down feeling','I was disappointed with the result.','Tôi thất vọng với kết quả.'],
  ['confident','/ˈkɑːn.fɪ.dənt/','adj','tự tin','feeling sure','She is very confident.','Cô ấy rất tự tin.'],
  ['embarrassed','/ɪmˈber.əst/','adj','xấu hổ','feeling ashamed','He felt embarrassed.','Anh ấy cảm thấy xấu hổ.'],
  ['grateful','/ˈɡreɪt.fəl/','adj','biết ơn','feeling thankful','I am grateful for your help.','Tôi biết ơn sự giúp đỡ của bạn.'],
  ['confused','/kənˈfjuːzd/','adj','bối rối','not understanding','I am confused by this question.','Tôi bối rối với câu hỏi này.'],
  ['calm','/kɑːm/','adj','bình tĩnh','feeling peaceful','Stay calm and relax.','Giữ bình tĩnh và thư giãn.'],
  ['kind','/kaɪnd/','adj','tốt bụng','caring and nice','She is a very kind person.','Cô ấy là người rất tốt bụng.'],
  ['polite','/pəˈlaɪt/','adj','lịch sự','showing good manners','He is always polite.','Anh ấy luôn lịch sự.'],
  ['shy','/ʃaɪ/','adj','nhút nhát','feeling timid','The girl is shy.','Cô bé nhút nhát.'],
  ['laugh','/læf/','verb','cười','make happy sounds','We laugh at the joke.','Chúng tôi cười vì câu đùa.'],
  ['cry','/kraɪ/','verb','khóc','shed tears','The baby is crying.','Em bé đang khóc.'],
  ['smile','/smaɪl/','verb','mỉm cười','show happiness','She smiles at me.','Cô ấy mỉm cười với tôi.'],
  ['feel','/fiːl/','verb','cảm thấy','to experience','How do you feel today?','Hôm nay bạn cảm thấy thế nào?'],
  ['love','/lʌv/','verb','yêu','deep affection','I love my family.','Tôi yêu gia đình.'],
  ['hate','/heɪt/','verb','ghét','strong dislike','I hate being late.','Tôi ghét bị muộn.'],
  ['miss','/mɪs/','verb','nhớ','feel absence of','I miss my friends.','Tôi nhớ bạn bè.'],
  ['hope','/hoʊp/','verb','hy vọng','to wish for','I hope you feel better.','Tôi hy vọng bạn khỏe hơn.']),
  // 12. School & Education
  ...W('School & Education',
  ['school','/skuːl/','noun','trường học','place of learning','I go to school every day.','Tôi đi học mỗi ngày.'],
  ['teacher','/ˈtiː.tʃɚ/','noun','giáo viên','person who teaches','Our teacher is very nice.','Giáo viên chúng tôi rất tốt.'],
  ['student','/ˈstuː.dənt/','noun','học sinh','person who learns','She is a good student.','Cô ấy là học sinh giỏi.'],
  ['class','/klæs/','noun','lớp học','a lesson group','We have English class today.','Hôm nay có lớp tiếng Anh.'],
  ['homework','/ˈhoʊm.wɜːrk/','noun','bài tập về nhà','work done at home','I finished my homework.','Tôi làm xong bài tập.'],
  ['exam','/ɪɡˈzæm/','noun','bài thi','a test','The exam is next week.','Kỳ thi tuần sau.'],
  ['book','/bʊk/','noun','sách','written work','I read many books.','Tôi đọc nhiều sách.'],
  ['pen','/pen/','noun','bút mực','writing tool','Give me a pen, please.','Cho tôi mượn bút.'],
  ['pencil','/ˈpen.səl/','noun','bút chì','drawing tool','I draw with a pencil.','Tôi vẽ bằng bút chì.'],
  ['notebook','/ˈnoʊt.bʊk/','noun','vở','writing pad','Write it in your notebook.','Ghi vào vở đi.'],
  ['learn','/lɜːrn/','verb','học','to get knowledge','I learn new words daily.','Tôi học từ mới mỗi ngày.'],
  ['teach','/tiːtʃ/','verb','dạy','to give lessons','She teaches math.','Cô ấy dạy toán.'],
  ['answer','/ˈæn.sɚ/','noun','câu trả lời','a reply','What is the answer?','Đáp án là gì?'],
  ['question','/ˈkwes.tʃən/','noun','câu hỏi','something asked','I have a question.','Tôi có câu hỏi.'],
  ['practice','/ˈpræk.tɪs/','verb','luyện tập','to do repeatedly','Practice makes perfect.','Luyện tập tạo hoàn hảo.'],
  ['mistake','/mɪˈsteɪk/','noun','lỗi sai','an error','Everyone makes mistakes.','Ai cũng mắc lỗi.'],
  ['correct','/kəˈrekt/','adj','đúng','without errors','Your answer is correct.','Câu trả lời của bạn đúng.'],
  ['wrong','/rɑːŋ/','adj','sai','not correct','That is the wrong answer.','Đó là đáp án sai.'],
  ['easy','/ˈiː.zi/','adj','dễ','not difficult','This exercise is easy.','Bài tập này dễ.'],
  ['difficult','/ˈdɪf.ɪ.kəlt/','adj','khó','not easy','Math is difficult for me.','Toán khó với tôi.'],
  ['remember','/rɪˈmem.bɚ/','verb','nhớ','to recall','I remember your name.','Tôi nhớ tên bạn.'],
  ['forget','/fɚˈɡet/','verb','quên','to not remember','Do not forget your homework.','Đừng quên bài tập nhé.'],
  ['explain','/ɪkˈspleɪn/','verb','giải thích','to make clear','Can you explain this?','Bạn giải thích được không?'],
  ['page','/peɪdʒ/','noun','trang','one side of paper','Open page twenty.','Mở trang hai mươi.'],
  ['library','/ˈlaɪ.brer.i/','noun','thư viện','book lending place','I study at the library.','Tôi học ở thư viện.'],
  ['computer','/kəmˈpjuː.t̬ɚ/','noun','máy tính','electronic machine','I use the computer daily.','Tôi dùng máy tính hàng ngày.'],
  ['internet','/ˈɪn.t̬ɚ.net/','noun','mạng internet','worldwide network','I search on the internet.','Tôi tìm trên mạng.'],
  ['language','/ˈlæŋ.ɡwɪdʒ/','noun','ngôn ngữ','system of words','English is a language.','Tiếng Anh là một ngôn ngữ.'],
  ['dictionary','/ˈdɪk.ʃən.er.i/','noun','từ điển','word reference book','I use a dictionary a lot.','Tôi dùng từ điển nhiều.'],
  ['degree','/dɪˈɡriː/','noun','bằng cấp','academic qualification','She has a university degree.','Cô ấy có bằng đại học.']),
  // 13. Work & Jobs
  ...W('Work & Jobs',
  ['job','/dʒɑːb/','noun','công việc','paid work','I have a new job.','Tôi có công việc mới.'],
  ['office','/ˈɑː.fɪs/','noun','văn phòng','workplace','I work in an office.','Tôi làm ở văn phòng.'],
  ['boss','/bɑːs/','noun','sếp','person in charge','My boss is very kind.','Sếp tôi rất tốt.'],
  ['colleague','/ˈkɑː.liːɡ/','noun','đồng nghiệp','work partner','She is my colleague.','Cô ấy là đồng nghiệp tôi.'],
  ['salary','/ˈsæl.ɚ.i/','noun','lương','money earned','My salary is good.','Lương tôi khá tốt.'],
  ['meeting','/ˈmiː.t̬ɪŋ/','noun','cuộc họp','group discussion','We have a meeting at ten.','Chúng tôi họp lúc mười giờ.'],
  ['email','/ˈiː.meɪl/','noun','email','electronic message','I send an email every day.','Tôi gửi email mỗi ngày.'],
  ['phone','/foʊn/','noun','điện thoại','communication device','Answer the phone, please.','Trả lời điện thoại đi.'],
  ['busy','/ˈbɪz.i/','adj','bận','having much to do','I am very busy today.','Hôm nay tôi rất bận.'],
  ['finish','/ˈfɪn.ɪʃ/','verb','hoàn thành','to complete','I finish work at five.','Tôi xong việc lúc năm giờ.'],
  ['start','/stɑːrt/','verb','bắt đầu','to begin','We start at nine.','Chúng tôi bắt đầu lúc chín giờ.'],
  ['plan','/plæn/','noun','kế hoạch','a proposal','What is your plan?','Kế hoạch của bạn là gì?'],
  ['project','/ˈprɑː.dʒekt/','noun','dự án','planned work','I work on a new project.','Tôi làm dự án mới.'],
  ['experience','/ɪkˈspɪr.i.əns/','noun','kinh nghiệm','gained knowledge','She has ten years of experience.','Cô ấy có mười năm kinh nghiệm.'],
  ['interview','/ˈɪn.t̬ɚ.vjuː/','noun','phỏng vấn','job meeting','I have an interview tomorrow.','Ngày mai tôi có phỏng vấn.'],
  ['company','/ˈkʌm.pə.ni/','noun','công ty','business organization','I work for a big company.','Tôi làm cho công ty lớn.'],
  ['manager','/ˈmæn.ɪ.dʒɚ/','noun','quản lý','person who manages','She is a good manager.','Cô ấy là quản lý giỏi.'],
  ['customer','/ˈkʌs.tə.mɚ/','noun','khách hàng','a buyer','The customer is always right.','Khách hàng luôn đúng.'],
  ['team','/tiːm/','noun','đội nhóm','a working group','We work as a team.','Chúng tôi làm việc theo nhóm.'],
  ['report','/rɪˈpɔːrt/','noun','báo cáo','formal account','I write a report.','Tôi viết báo cáo.'],
  ['skill','/skɪl/','noun','kỹ năng','ability from practice','Communication is an important skill.','Giao tiếp là kỹ năng quan trọng.'],
  ['apply','/əˈplaɪ/','verb','ứng tuyển','to request formally','I apply for the job.','Tôi ứng tuyển công việc.'],
  ['decide','/dɪˈsaɪd/','verb','quyết định','to make a choice','I decide to study abroad.','Tôi quyết định đi du học.'],
  ['solve','/sɑːlv/','verb','giải quyết','to find answer','We solve problems together.','Chúng tôi giải quyết cùng nhau.'],
  ['improve','/ɪmˈpruːv/','verb','cải thiện','to make better','I want to improve my English.','Tôi muốn cải thiện tiếng Anh.'],
  ['succeed','/səkˈsiːd/','verb','thành công','to achieve goal','Hard work helps you succeed.','Chăm chỉ giúp bạn thành công.'],
  ['fail','/feɪl/','verb','thất bại','to not succeed','Do not be afraid to fail.','Đừng sợ thất bại.'],
  ['earn','/ɜːrn/','verb','kiếm được','to get money','She earns a good salary.','Cô ấy kiếm lương tốt.'],
  ['hire','/haɪɚ/','verb','thuê, tuyển','to employ','They hire new staff.','Họ tuyển nhân viên mới.'],
  ['retire','/rɪˈtaɪɚ/','verb','nghỉ hưu','to stop working','He will retire next year.','Ông ấy nghỉ hưu năm sau.']),
  // 14. House & Home
  ...W('House & Home',
  ['house','/haʊs/','noun','nhà','a building to live in','I live in a big house.','Tôi sống trong nhà lớn.'],
  ['apartment','/əˈpɑːrt.mənt/','noun','căn hộ','a flat','She lives in an apartment.','Cô ấy sống trong căn hộ.'],
  ['room','/ruːm/','noun','phòng','a space in a house','My room is small.','Phòng tôi nhỏ.'],
  ['bedroom','/ˈbed.ruːm/','noun','phòng ngủ','room to sleep in','I sleep in my bedroom.','Tôi ngủ trong phòng ngủ.'],
  ['bathroom','/ˈbæθ.ruːm/','noun','phòng tắm','room for washing','The bathroom is clean.','Phòng tắm sạch.'],
  ['kitchen','/ˈkɪtʃ.ən/','noun','nhà bếp','room for cooking','She cooks in the kitchen.','Cô ấy nấu ăn trong bếp.'],
  ['living room','/ˈlɪv.ɪŋ ruːm/','noun','phòng khách','main room','We watch TV in the living room.','Chúng tôi xem TV ở phòng khách.'],
  ['door','/dɔːr/','noun','cửa','entrance barrier','Please close the door.','Hãy đóng cửa lại.'],
  ['window','/ˈwɪn.doʊ/','noun','cửa sổ','opening in wall','Open the window, please.','Mở cửa sổ ra.'],
  ['floor','/flɔːr/','noun','sàn nhà','bottom surface','The floor is very clean.','Sàn nhà rất sạch.'],
  ['wall','/wɑːl/','noun','tường','vertical surface','The wall is painted white.','Tường sơn trắng.'],
  ['roof','/ruːf/','noun','mái nhà','top of building','The roof is red.','Mái nhà màu đỏ.'],
  ['garden','/ˈɡɑːr.dən/','noun','vườn','outdoor area','I plant flowers in the garden.','Tôi trồng hoa trong vườn.'],
  ['table','/ˈteɪ.bəl/','noun','bàn','furniture for eating','Put it on the table.','Đặt lên bàn.'],
  ['chair','/tʃer/','noun','ghế','seat furniture','Sit on the chair.','Ngồi lên ghế.'],
  ['bed','/bed/','noun','giường','furniture to sleep on','I lie on my bed.','Tôi nằm trên giường.'],
  ['lamp','/læmp/','noun','đèn','light source','Turn on the lamp.','Bật đèn lên.'],
  ['mirror','/ˈmɪr.ɚ/','noun','gương','reflective surface','I look in the mirror.','Tôi nhìn vào gương.'],
  ['key','/kiː/','noun','chìa khóa','door opener','I lost my key.','Tôi mất chìa khóa.'],
  ['neighbor','/ˈneɪ.bɚ/','noun','hàng xóm','person next door','My neighbor is friendly.','Hàng xóm tôi thân thiện.'],
  ['furniture','/ˈfɜːr.nɪ.tʃɚ/','noun','nội thất','things in a room','We buy new furniture.','Chúng tôi mua nội thất mới.'],
  ['sofa','/ˈsoʊ.fə/','noun','ghế sofa','soft long seat','Sit on the sofa.','Ngồi lên sofa.'],
  ['fridge','/frɪdʒ/','noun','tủ lạnh','cooling device','The milk is in the fridge.','Sữa ở trong tủ lạnh.'],
  ['cook','/kʊk/','verb','nấu ăn','to prepare food','I cook dinner every day.','Tôi nấu cơm mỗi ngày.'],
  ['repair','/rɪˈper/','verb','sửa chữa','to fix','I repair the chair.','Tôi sửa ghế.'],
  ['move','/muːv/','verb','chuyển nhà','to change home','We move to a new house.','Chúng tôi chuyển nhà mới.'],
  ['rent','/rent/','verb','thuê','to pay to use','I rent an apartment.','Tôi thuê căn hộ.'],
  ['build','/bɪld/','verb','xây dựng','to construct','They build a new house.','Họ xây nhà mới.'],
  ['decorate','/ˈdek.ə.reɪt/','verb','trang trí','to make pretty','We decorate the room.','Chúng tôi trang trí phòng.'],
  ['comfortable','/ˈkʌmf.tɚ.bəl/','adj','thoải mái','giving ease','The bed is comfortable.','Giường rất thoải mái.']),
  // 15. Technology
  ...W('Technology',
  ['phone','/foʊn/','noun','điện thoại','mobile device','I use my phone a lot.','Tôi dùng điện thoại nhiều.'],
  ['laptop','/ˈlæp.tɑːp/','noun','máy tính xách tay','portable computer','I work on my laptop.','Tôi làm việc trên laptop.'],
  ['tablet','/ˈtæb.lɪt/','noun','máy tính bảng','flat computer','She reads on her tablet.','Cô ấy đọc trên máy tính bảng.'],
  ['screen','/skriːn/','noun','màn hình','display surface','The screen is very bright.','Màn hình rất sáng.'],
  ['keyboard','/ˈkiː.bɔːrd/','noun','bàn phím','typing device','I type on the keyboard.','Tôi gõ trên bàn phím.'],
  ['mouse','/maʊs/','noun','chuột máy tính','pointing device','Click the mouse button.','Nhấn chuột.'],
  ['password','/ˈpæs.wɜːrd/','noun','mật khẩu','secret code','Do not share your password.','Đừng chia sẻ mật khẩu.'],
  ['website','/ˈweb.saɪt/','noun','trang web','internet page','Visit our website.','Ghé thăm trang web của chúng tôi.'],
  ['app','/æp/','noun','ứng dụng','software program','I download a new app.','Tôi tải ứng dụng mới.'],
  ['download','/ˈdaʊn.loʊd/','verb','tải xuống','to save from net','Download this file.','Tải file này xuống.'],
  ['upload','/ˈʌp.loʊd/','verb','tải lên','to send to net','Upload your photo.','Tải ảnh lên.'],
  ['search','/sɜːrtʃ/','verb','tìm kiếm','to look for','I search on Google.','Tôi tìm trên Google.'],
  ['message','/ˈmes.ɪdʒ/','noun','tin nhắn','a sent text','I send a message.','Tôi gửi tin nhắn.'],
  ['video','/ˈvɪd.i.oʊ/','noun','video','moving images','I watch videos online.','Tôi xem video trên mạng.'],
  ['photo','/ˈfoʊ.t̬oʊ/','noun','ảnh','a picture','I take a photo.','Tôi chụp ảnh.'],
  ['camera','/ˈkæm.ɚ.ə/','noun','máy ảnh','photo device','My phone has a good camera.','Điện thoại tôi có camera tốt.'],
  ['battery','/ˈbæt̬.ɚ.i/','noun','pin','power source','My battery is low.','Pin tôi sắp hết.'],
  ['charger','/ˈtʃɑːr.dʒɚ/','noun','sạc','power cable','I need a charger.','Tôi cần sạc.'],
  ['wifi','/ˈwaɪ.faɪ/','noun','wifi','wireless internet','Is there wifi here?','Ở đây có wifi không?'],
  ['online','/ˌɑːnˈlaɪn/','adj','trực tuyến','on the internet','I study online.','Tôi học trực tuyến.'],
  ['offline','/ˌɑːfˈlaɪn/','adj','ngoại tuyến','not connected','The app works offline.','Ứng dụng hoạt động ngoại tuyến.'],
  ['update','/ˌʌpˈdeɪt/','verb','cập nhật','to make current','Please update the app.','Hãy cập nhật ứng dụng.'],
  ['delete','/dɪˈliːt/','verb','xóa','to remove','Delete this file.','Xóa file này.'],
  ['save','/seɪv/','verb','lưu','to keep data','Save the document.','Lưu tài liệu.'],
  ['share','/ʃer/','verb','chia sẻ','to give to others','Share this link.','Chia sẻ liên kết này.'],
  ['click','/klɪk/','verb','nhấn','to press button','Click this button.','Nhấn nút này.'],
  ['connect','/kəˈnekt/','verb','kết nối','to link together','Connect to the wifi.','Kết nối wifi.'],
  ['install','/ɪnˈstɑːl/','verb','cài đặt','to set up','Install this app.','Cài đặt ứng dụng này.'],
  ['copy','/ˈkɑː.pi/','verb','sao chép','to duplicate','Copy this text.','Sao chép văn bản này.'],
  ['print','/prɪnt/','verb','in','to put on paper','Print this document.','In tài liệu này.']),
];
