// Seed data part 2: Topics 6-10
const W=(t,...d)=>d.map(r=>({word:r[0],ipa:r[1],pos:r[2],vi:r[3],en:r[4],ex_en:r[5],ex_vi:r[6],topic:t,level:'A1',lang:'en'}));
export const WORDS_PART2 = [
  ...W('Daily Activities',
  ['wake up','/weɪk ʌp/','verb','thức dậy','to stop sleeping','I wake up at six.','Tôi thức dậy lúc sáu giờ.'],
  ['sleep','/sliːp/','verb','ngủ','to rest at night','I sleep eight hours.','Tôi ngủ tám tiếng.'],
  ['walk','/wɑːk/','verb','đi bộ','to move on foot','I walk to school.','Tôi đi bộ đến trường.'],
  ['run','/rʌn/','verb','chạy','to move fast','I run every morning.','Tôi chạy bộ mỗi sáng.'],
  ['work','/wɜːrk/','verb','làm việc','to do a job','I work from nine to five.','Tôi làm từ chín đến năm.'],
  ['study','/ˈstʌd.i/','verb','học','to learn','I study English every day.','Tôi học tiếng Anh mỗi ngày.'],
  ['read','/riːd/','verb','đọc','to look at text','I read a book at night.','Tôi đọc sách buổi tối.'],
  ['write','/raɪt/','verb','viết','to put words on paper','Please write your name.','Hãy viết tên bạn.'],
  ['listen','/ˈlɪs.ən/','verb','nghe','pay attention to sound','I listen to music.','Tôi nghe nhạc.'],
  ['watch','/wɑːtʃ/','verb','xem','to look at something','I watch TV at night.','Tôi xem TV buổi tối.'],
  ['play','/pleɪ/','verb','chơi','to do for fun','Children play in the park.','Trẻ em chơi trong công viên.'],
  ['wash','/wɑːʃ/','verb','rửa, giặt','to clean with water','I wash my hands.','Tôi rửa tay.'],
  ['clean','/kliːn/','verb','dọn dẹp','to make tidy','I clean my room.','Tôi dọn phòng.'],
  ['take','/teɪk/','verb','lấy','to get something','Take your umbrella.','Lấy ô đi.'],
  ['make','/meɪk/','verb','làm, tạo','to create','I make my bed every day.','Tôi dọn giường mỗi ngày.'],
  ['open','/ˈoʊ.pən/','verb','mở','to make not closed','Open the door, please.','Mở cửa ra, làm ơn.'],
  ['close','/kloʊz/','verb','đóng','to shut','Close the window.','Đóng cửa sổ lại.'],
  ['sit','/sɪt/','verb','ngồi','to be seated','Please sit down.','Hãy ngồi xuống.'],
  ['stand','/stænd/','verb','đứng','to be on your feet','Stand up, please.','Đứng lên, làm ơn.'],
  ['buy','/baɪ/','verb','mua','to purchase','I want to buy a book.','Tôi muốn mua sách.'],
  ['give','/ɡɪv/','verb','cho, tặng','to hand to someone','Give me the pen.','Đưa tôi cây bút.'],
  ['drive','/draɪv/','verb','lái xe','to operate a vehicle','I drive to work.','Tôi lái xe đi làm.'],
  ['wait','/weɪt/','verb','đợi','to stay until','Wait for me!','Đợi tôi với!'],
  ['use','/juːz/','verb','sử dụng','to put into action','I use my phone a lot.','Tôi dùng điện thoại nhiều.'],
  ['want','/wɑːnt/','verb','muốn','to desire','I want a glass of water.','Tôi muốn một ly nước.'],
  ['need','/niːd/','verb','cần','to require','I need your help.','Tôi cần sự giúp đỡ.'],
  ['like','/laɪk/','verb','thích','to enjoy','I like swimming.','Tôi thích bơi.'],
  ['look','/lʊk/','verb','nhìn','to direct eyes at','Look at this picture!','Nhìn bức ảnh này!'],
  ['think','/θɪŋk/','verb','nghĩ','to use the mind','I think this is correct.','Tôi nghĩ đây là đúng.'],
  ['try','/traɪ/','verb','thử','to attempt','Try again!','Thử lại đi!']),
  ...W('Weather',
  ['weather','/ˈweð.ɚ/','noun','thời tiết','atmospheric condition','The weather is nice today.','Hôm nay thời tiết đẹp.'],
  ['sun','/sʌn/','noun','mặt trời','the star in our sky','The sun is shining.','Mặt trời đang tỏa sáng.'],
  ['rain','/reɪn/','noun','mưa','water from clouds','It will rain tomorrow.','Ngày mai trời sẽ mưa.'],
  ['cloud','/klaʊd/','noun','đám mây','white mass in sky','There are many clouds.','Có nhiều đám mây.'],
  ['wind','/wɪnd/','noun','gió','moving air','The wind is strong today.','Hôm nay gió mạnh.'],
  ['snow','/snoʊ/','noun','tuyết','frozen white flakes','Children love snow.','Trẻ em thích tuyết.'],
  ['hot','/hɑːt/','adj','nóng','high temperature','It is very hot today.','Hôm nay trời rất nóng.'],
  ['cold','/koʊld/','adj','lạnh','low temperature','It is cold in winter.','Mùa đông trời lạnh.'],
  ['warm','/wɔːrm/','adj','ấm','pleasantly warm','Spring is warm.','Mùa xuân ấm áp.'],
  ['cool','/kuːl/','adj','mát','slightly cold','The evening is cool.','Buổi tối mát mẻ.'],
  ['sunny','/ˈsʌn.i/','adj','nắng','full of sunshine','It is a sunny day.','Hôm nay trời nắng.'],
  ['cloudy','/ˈklaʊ.di/','adj','nhiều mây','covered by clouds','It is cloudy today.','Hôm nay nhiều mây.'],
  ['rainy','/ˈreɪ.ni/','adj','mưa','having rain','Rainy days make me sleepy.','Ngày mưa làm tôi buồn ngủ.'],
  ['windy','/ˈwɪn.di/','adj','nhiều gió','with strong wind','It is very windy outside.','Bên ngoài gió mạnh.'],
  ['storm','/stɔːrm/','noun','bão','violent weather','A storm is coming.','Bão sắp đến.'],
  ['thunder','/ˈθʌn.dɚ/','noun','sấm','loud sound','I hear thunder.','Tôi nghe tiếng sấm.'],
  ['temperature','/ˈtem.pɚ.ə.tʃɚ/','noun','nhiệt độ','degree of heat','It is 30 degrees.','Nhiệt độ 30 độ.'],
  ['season','/ˈsiː.zən/','noun','mùa','a time of year','What is your favorite season?','Mùa yêu thích của bạn?'],
  ['spring','/sprɪŋ/','noun','mùa xuân','after winter','Flowers bloom in spring.','Hoa nở vào mùa xuân.'],
  ['summer','/ˈsʌm.ɚ/','noun','mùa hè','the hottest season','Summer is very hot.','Mùa hè rất nóng.'],
  ['autumn','/ˈɑː.t̬əm/','noun','mùa thu','after summer','Leaves fall in autumn.','Lá rụng vào mùa thu.'],
  ['winter','/ˈwɪn.t̬ɚ/','noun','mùa đông','coldest season','I wear a coat in winter.','Tôi mặc áo khoác mùa đông.'],
  ['sky','/skaɪ/','noun','bầu trời','the space above','The sky is very clear.','Bầu trời rất trong.'],
  ['umbrella','/ʌmˈbrel.ə/','noun','ô, dù','rain protection','Do not forget your umbrella!','Đừng quên mang ô!'],
  ['wet','/wet/','adj','ướt','covered with water','The road is wet.','Đường ướt.'],
  ['dry','/draɪ/','adj','khô','without water','The clothes are dry.','Quần áo đã khô.'],
  ['fog','/fɑːɡ/','noun','sương mù','thick cloud near ground','There is fog this morning.','Sáng nay có sương mù.'],
  ['rainbow','/ˈreɪn.boʊ/','noun','cầu vồng','colored arc in sky','Look at the rainbow!','Nhìn cầu vồng kìa!'],
  ['ice','/aɪs/','noun','đá, băng','frozen water','The road has ice on it.','Đường có băng.'],
  ['degree','/dɪˈɡriː/','noun','độ','unit of temperature','It is 25 degrees today.','Hôm nay 25 độ.']),
  ...W('Travel',
  ['travel','/ˈtræv.əl/','verb','du lịch','to go to places','I love to travel.','Tôi thích du lịch.'],
  ['airport','/ˈer.pɔːrt/','noun','sân bay','where planes land','We go to the airport.','Chúng tôi đến sân bay.'],
  ['hotel','/hoʊˈtel/','noun','khách sạn','place to stay','The hotel is very nice.','Khách sạn rất đẹp.'],
  ['ticket','/ˈtɪk.ɪt/','noun','vé','pass for travel','I bought a plane ticket.','Tôi mua vé máy bay.'],
  ['passport','/ˈpæs.pɔːrt/','noun','hộ chiếu','travel document','Show me your passport.','Cho tôi xem hộ chiếu.'],
  ['map','/mæp/','noun','bản đồ','diagram of area','I need a map.','Tôi cần bản đồ.'],
  ['bus','/bʌs/','noun','xe buýt','large road vehicle','I take the bus to work.','Tôi đi xe buýt đi làm.'],
  ['train','/treɪn/','noun','xe lửa','rail vehicle','The train is fast.','Xe lửa chạy nhanh.'],
  ['car','/kɑːr/','noun','xe hơi','motor vehicle','I drive my car to work.','Tôi lái xe đi làm.'],
  ['taxi','/ˈtæk.si/','noun','taxi','hired car','Call a taxi, please.','Gọi taxi đi.'],
  ['street','/striːt/','noun','đường phố','a public road','This street is very busy.','Con đường này rất đông.'],
  ['city','/ˈsɪt̬.i/','noun','thành phố','a large town','I live in a big city.','Tôi sống ở thành phố lớn.'],
  ['country','/ˈkʌn.tri/','noun','quốc gia','a nation','What country are you from?','Bạn đến từ nước nào?'],
  ['beach','/biːtʃ/','noun','bãi biển','sandy shore','Let us go to the beach!','Chúng ta đi biển đi!'],
  ['mountain','/ˈmaʊn.t̬ən/','noun','núi','a very high hill','The mountain is beautiful.','Ngọn núi rất đẹp.'],
  ['river','/ˈrɪv.ɚ/','noun','sông','a large stream','The river is very long.','Con sông rất dài.'],
  ['park','/pɑːrk/','noun','công viên','public green area','I walk in the park.','Tôi đi dạo công viên.'],
  ['museum','/mjuːˈziː.əm/','noun','bảo tàng','place for exhibits','We visit the museum.','Chúng tôi tham quan bảo tàng.'],
  ['left','/left/','noun','bên trái','opposite of right','Turn left here.','Rẽ trái ở đây.'],
  ['right','/raɪt/','noun','bên phải','opposite of left','Turn right at the corner.','Rẽ phải ở góc.'],
  ['near','/nɪr/','prep','gần','not far from','The school is near.','Trường gần nhà tôi.'],
  ['far','/fɑːr/','adj','xa','at great distance','The airport is far away.','Sân bay rất xa.'],
  ['here','/hɪr/','adv','ở đây','in this place','I am here.','Tôi ở đây.'],
  ['there','/ðer/','adv','ở đó','in that place','The shop is over there.','Cửa hàng ở đằng kia.'],
  ['where','/wer/','adv','ở đâu','in what place','Where is the bathroom?','Nhà vệ sinh ở đâu?'],
  ['bridge','/brɪdʒ/','noun','cầu','structure over water','We cross the bridge.','Chúng tôi qua cầu.'],
  ['road','/roʊd/','noun','con đường','path for vehicles','The road is very long.','Con đường rất dài.'],
  ['trip','/trɪp/','noun','chuyến đi','a journey','Have a nice trip!','Chúc chuyến đi vui vẻ!'],
  ['visit','/ˈvɪz.ɪt/','verb','thăm','to go see','I visit my grandmother.','Tôi đi thăm bà.'],
  ['arrive','/əˈraɪv/','verb','đến nơi','to reach a place','We arrive at six.','Chúng tôi đến lúc sáu giờ.']),
  ...W('Shopping',
  ['shop','/ʃɑːp/','noun','cửa hàng','place to buy','I go to the shop.','Tôi đi cửa hàng.'],
  ['money','/ˈmʌn.i/','noun','tiền','used to buy things','I do not have enough money.','Tôi không có đủ tiền.'],
  ['price','/praɪs/','noun','giá','cost of something','What is the price?','Giá bao nhiêu?'],
  ['cheap','/tʃiːp/','adj','rẻ','low cost','This shirt is cheap.','Cái áo này rẻ.'],
  ['expensive','/ɪkˈspen.sɪv/','adj','đắt','high cost','That bag is too expensive.','Cái túi đó quá đắt.'],
  ['pay','/peɪ/','verb','trả tiền','give money for','I pay by card.','Tôi trả bằng thẻ.'],
  ['sell','/sel/','verb','bán','give for money','They sell fresh fruit.','Họ bán trái cây tươi.'],
  ['market','/ˈmɑːr.kɪt/','noun','chợ','buy and sell place','I go to the market.','Tôi đi chợ.'],
  ['bag','/bæɡ/','noun','túi','container to carry','I carry a big bag.','Tôi mang túi lớn.'],
  ['clothes','/kloʊðz/','noun','quần áo','items you wear','I buy new clothes.','Tôi mua quần áo mới.'],
  ['shirt','/ʃɜːrt/','noun','áo sơ mi','upper body clothing','He wears a white shirt.','Anh ấy mặc áo trắng.'],
  ['shoes','/ʃuːz/','noun','giày','foot covering','I need new shoes.','Tôi cần giày mới.'],
  ['hat','/hæt/','noun','mũ','head covering','She wears a hat.','Cô ấy đội mũ.'],
  ['dress','/dres/','noun','váy','a woman garment','She wears a red dress.','Cô ấy mặc váy đỏ.'],
  ['size','/saɪz/','noun','kích cỡ','how big','What size do you need?','Bạn cần cỡ nào?'],
  ['try on','/traɪ ɑːn/','verb','thử đồ','test clothing','Can I try on this shirt?','Tôi thử áo này được không?'],
  ['change','/tʃeɪndʒ/','noun','tiền thối','money returned','Here is your change.','Đây là tiền thối.'],
  ['how much','/haʊ mʌtʃ/','adv','bao nhiêu','asking for price','How much is this?','Cái này bao nhiêu?'],
  ['gift','/ɡɪft/','noun','quà tặng','a present','This is a gift for you.','Đây là quà cho bạn.'],
  ['free','/friː/','adj','miễn phí','no cost','This sample is free.','Mẫu thử này miễn phí.'],
  ['sale','/seɪl/','noun','giảm giá','reduced prices','The shoes are on sale.','Giày đang giảm giá.'],
  ['receipt','/rɪˈsiːt/','noun','hóa đơn','proof of purchase','Keep the receipt.','Giữ hóa đơn lại.'],
  ['wallet','/ˈwɑː.lɪt/','noun','ví','money holder','My wallet is in my bag.','Ví tôi ở trong túi.'],
  ['card','/kɑːrd/','noun','thẻ','payment card','I pay by credit card.','Tôi trả bằng thẻ.'],
  ['cash','/kæʃ/','noun','tiền mặt','physical money','Do you accept cash?','Bạn nhận tiền mặt không?'],
  ['open','/ˈoʊ.pən/','adj','mở cửa','not closed','Is the shop open?','Cửa hàng mở cửa không?'],
  ['closed','/kloʊzd/','adj','đóng cửa','not open','The store is closed.','Cửa hàng đóng cửa.'],
  ['order','/ˈɔːr.dɚ/','verb','đặt hàng','to request','I want to order online.','Tôi muốn đặt hàng online.'],
  ['return','/rɪˈtɜːrn/','verb','trả lại','to give back','Can I return this?','Tôi có thể trả lại không?'],
  ['discount','/ˈdɪs.kaʊnt/','noun','chiết khấu','price reduction','Is there a discount?','Có giảm giá không?']),
  ...W('Body & Health',
  ['head','/hed/','noun','đầu','top of body','My head hurts.','Đầu tôi đau.'],
  ['eye','/aɪ/','noun','mắt','organ of sight','She has blue eyes.','Cô ấy có mắt xanh.'],
  ['ear','/ɪr/','noun','tai','organ of hearing','I hear with my ears.','Tôi nghe bằng tai.'],
  ['nose','/noʊz/','noun','mũi','organ of smell','My nose is running.','Mũi tôi bị chảy nước.'],
  ['mouth','/maʊθ/','noun','miệng','opening for eating','Open your mouth wide.','Mở miệng to ra.'],
  ['hand','/hænd/','noun','bàn tay','end of the arm','Wash your hands.','Rửa tay đi.'],
  ['arm','/ɑːrm/','noun','cánh tay','limb from shoulder','I broke my arm.','Tôi bị gãy tay.'],
  ['leg','/leɡ/','noun','chân','limb for walking','My leg is tired.','Chân tôi mỏi.'],
  ['foot','/fʊt/','noun','bàn chân','bottom of the leg','My foot hurts.','Bàn chân tôi đau.'],
  ['back','/bæk/','noun','lưng','rear of body','My back aches.','Lưng tôi đau.'],
  ['stomach','/ˈstʌm.ək/','noun','dạ dày, bụng','belly area','My stomach hurts.','Bụng tôi đau.'],
  ['tooth','/tuːθ/','noun','răng','bone in mouth','I have a toothache.','Tôi bị đau răng.'],
  ['hair','/her/','noun','tóc','strands on head','She has long hair.','Cô ấy có tóc dài.'],
  ['face','/feɪs/','noun','mặt','front of head','Wash your face.','Rửa mặt đi.'],
  ['finger','/ˈfɪŋ.ɡɚ/','noun','ngón tay','digit of hand','I cut my finger.','Tôi bị đứt ngón tay.'],
  ['sick','/sɪk/','adj','ốm, bệnh','not healthy','I feel sick today.','Hôm nay tôi bị ốm.'],
  ['healthy','/ˈhel.θi/','adj','khỏe mạnh','in good health','Exercise keeps you healthy.','Tập thể dục giúp khỏe mạnh.'],
  ['doctor','/ˈdɑːk.tɚ/','noun','bác sĩ','medical professional','I see the doctor.','Tôi đi khám bác sĩ.'],
  ['hospital','/ˈhɑː.spɪ.t̬əl/','noun','bệnh viện','medical care place','He is in the hospital.','Anh ấy ở bệnh viện.'],
  ['medicine','/ˈmed.ə.sən/','noun','thuốc','drug for illness','Take your medicine.','Uống thuốc đi.'],
  ['pain','/peɪn/','noun','cơn đau','physical suffering','I feel pain in my leg.','Tôi thấy đau ở chân.'],
  ['tired','/taɪɚd/','adj','mệt','needing rest','I am very tired.','Tôi rất mệt.'],
  ['strong','/strɑːŋ/','adj','khỏe, mạnh','having power','He is very strong.','Anh ấy rất khỏe.'],
  ['exercise','/ˈek.sɚ.saɪz/','noun','tập thể dục','physical activity','I do exercise daily.','Tôi tập thể dục hàng ngày.'],
  ['rest','/rest/','verb','nghỉ ngơi','to relax','You need to rest.','Bạn cần nghỉ ngơi.'],
  ['fever','/ˈfiː.vɚ/','noun','sốt','high body temperature','She has a fever.','Cô ấy bị sốt.'],
  ['cough','/kɑːf/','noun','ho','forcing air from lungs','I have a bad cough.','Tôi bị ho nặng.'],
  ['cold','/koʊld/','noun','cảm lạnh','common illness','I caught a cold.','Tôi bị cảm lạnh.'],
  ['hurt','/hɜːrt/','verb','đau','to feel pain','My knee hurts.','Đầu gối tôi đau.'],
  ['well','/wel/','adj','khỏe','in good health','I do not feel well.','Tôi không khỏe.']),
];
