// WordSpark Chinese HSK1 Seed Data Part 1 — 150 words, 5 topics
// Format: [word, pinyin, pos, vi, zh, ex_zh, ex_vi, strokes, radical]
const ZH=(t,...d)=>d.map(r=>({word:r[0],pinyin:r[1],pos:r[2],vi:r[3],zh:r[4],ex_zh:r[5],ex_vi:r[6],strokes:r[7],radical:r[8],topic:t,level:'HSK1',lang:'zh'}));
export const WORDS_ZH = [
  ...ZH('问候',
  ['你好','nǐ hǎo','intj','xin chào','打招呼用语','你好，很高兴认识你。','Xin chào, rất vui được gặp bạn.',13,'亻'],
  ['再见','zài jiàn','intj','tạm biệt','告别用语','再见，明天见！','Tạm biệt, mai gặp!',10,'冂'],
  ['谢谢','xiè xie','intj','cảm ơn','表示感谢','谢谢你的帮助。','Cảm ơn sự giúp đỡ của bạn.',21,'讠'],
  ['不客气','bú kè qi','intj','không có gì','回应感谢','不客气，应该的。','Không có gì, đáng lẽ phải vậy.',13,'一'],
  ['对不起','duì bu qǐ','intj','xin lỗi','表示歉意','对不起，我迟到了。','Xin lỗi, tôi đến muộn.',14,'寸'],
  ['没关系','méi guān xi','intj','không sao','回应道歉','没关系，没事的。','Không sao, không có gì.',19,'氵'],
  ['请','qǐng','verb','mời, xin','表示请求','请坐下。','Mời ngồi.',10,'讠'],
  ['早上好','zǎo shang hǎo','intj','chào buổi sáng','早晨打招呼','早上好，今天天气真好！','Chào buổi sáng, hôm nay thời tiết đẹp!',18,'日'],
  ['晚上好','wǎn shang hǎo','intj','chào buổi tối','晚上打招呼','晚上好，吃了吗？','Chào buổi tối, ăn chưa?',17,'日'],
  ['你好吗','nǐ hǎo ma','intj','bạn khỏe không','问候健康','你好吗？我很好。','Bạn khỏe không? Tôi rất khỏe.',16,'亻'],
  ['很好','hěn hǎo','adj','rất tốt','表示状态好','我很好，谢谢。','Tôi rất khỏe, cảm ơn.',15,'彳'],
  ['名字','míng zi','noun','tên','人的称呼','你的名字是什么？','Tên bạn là gì?',9,'夕'],
  ['叫','jiào','verb','tên là, gọi','称呼','我叫小明。','Tôi tên là Tiểu Minh.',5,'口'],
  ['认识','rèn shi','verb','quen biết','了解某人','很高兴认识你。','Rất vui được quen bạn.',11,'讠'],
  ['高兴','gāo xìng','adj','vui','感到快乐','我很高兴见到你。','Tôi rất vui được gặp bạn.',16,'亠'],
  ['欢迎','huān yíng','verb','chào mừng','表示迎接','欢迎来到中国！','Chào mừng đến Trung Quốc!',13,'欠'],
  ['先生','xiān shēng','noun','ông, ngài','对男性的尊称','李先生，您好！','Chào ông Lý!',11,'儿'],
  ['女士','nǚ shì','noun','bà, cô','对女性的尊称','王女士很漂亮。','Bà Vương rất xinh đẹp.',6,'女'],
  ['朋友','péng yǒu','noun','bạn bè','关系亲近的人','他是我的好朋友。','Anh ấy là bạn tốt của tôi.',12,'月'],
  ['老师','lǎo shī','noun','thầy/cô giáo','教学的人','老师好！','Chào thầy/cô!',12,'耂'],
  ['同学','tóng xué','noun','bạn học','一起学习的人','他是我的同学。','Anh ấy là bạn học của tôi.',14,'口'],
  ['大家','dà jiā','pron','mọi người','所有人','大家好！','Mọi người xin chào!',13,'大'],
  ['介绍','jiè shào','verb','giới thiệu','说明情况','我来介绍一下。','Tôi xin giới thiệu.',12,'亻'],
  ['姓','xìng','noun','họ','家族的名','你姓什么？','Bạn họ gì?',8,'女'],
  ['是','shì','verb','là','表示肯定','我是学生。','Tôi là học sinh.',9,'日'],
  ['什么','shén me','pron','cái gì','疑问代词','这是什么？','Đây là cái gì?',6,'亻'],
  ['哪里','nǎ lǐ','pron','ở đâu','询问地点','你家在哪里？','Nhà bạn ở đâu?',16,'口'],
  ['怎么','zěn me','pron','thế nào','询问方式','你怎么去学校？','Bạn đi học bằng cách nào?',13,'心'],
  ['谁','shéi','pron','ai','询问人','他是谁？','Anh ấy là ai?',10,'讠'],
  ['好的','hǎo de','intj','được, ok','表示同意','好的，没问题。','Được, không vấn đề.',14,'女']),
  ...ZH('数字与时间',
  ['一','yī','num','một','数字1','我有一本书。','Tôi có một quyển sách.',1,'一'],
  ['二','èr','num','hai','数字2','我有二个苹果。','Tôi có hai quả táo.',2,'二'],
  ['三','sān','num','ba','数字3','三个人来了。','Ba người đã đến.',3,'一'],
  ['四','sì','num','bốn','数字4','一年有四个季节。','Một năm có bốn mùa.',5,'囗'],
  ['五','wǔ','num','năm','数字5','我们五点见面。','Chúng ta gặp lúc năm giờ.',4,'一'],
  ['六','liù','num','sáu','数字6','六月很热。','Tháng sáu rất nóng.',4,'亠'],
  ['七','qī','num','bảy','数字7','一周有七天。','Một tuần có bảy ngày.',2,'一'],
  ['八','bā','num','tám','数字8','八点上课。','Tám giờ vào lớp.',2,'八'],
  ['九','jiǔ','num','chín','数字9','九月开学。','Tháng chín khai giảng.',2,'丿'],
  ['十','shí','num','mười','数字10','十个学生。','Mười học sinh.',2,'十'],
  ['百','bǎi','num','trăm','数字100','一百块钱。','Một trăm đồng.',6,'白'],
  ['千','qiān','num','nghìn','数字1000','一千米。','Một nghìn mét.',3,'十'],
  ['零','líng','num','không, số 0','数字0','零下五度。','Âm năm độ.',13,'雨'],
  ['今天','jīn tiān','noun','hôm nay','这一天','今天星期几？','Hôm nay thứ mấy?',8,'人'],
  ['明天','míng tiān','noun','ngày mai','下一天','明天见！','Mai gặp!',12,'日'],
  ['昨天','zuó tiān','noun','hôm qua','前一天','昨天下雨了。','Hôm qua trời mưa.',13,'日'],
  ['年','nián','noun','năm','十二个月','新年快乐！','Chúc mừng năm mới!',6,'干'],
  ['月','yuè','noun','tháng','一年的十二分之一','一月很冷。','Tháng một rất lạnh.',4,'月'],
  ['日','rì','noun','ngày','一天','今日天气好。','Hôm nay thời tiết đẹp.',4,'日'],
  ['星期','xīng qī','noun','tuần','七天为一周','星期一上班。','Thứ hai đi làm.',17,'日'],
  ['小时','xiǎo shí','noun','giờ','六十分钟','一个小时。','Một tiếng đồng hồ.',13,'小'],
  ['分钟','fēn zhōng','noun','phút','六十秒','等我五分钟。','Đợi tôi năm phút.',12,'刀'],
  ['现在','xiàn zài','noun','bây giờ','此刻','现在几点？','Bây giờ mấy giờ?',14,'王'],
  ['时候','shí hou','noun','lúc, khi','某个时间','什么时候去？','Khi nào đi?',17,'日'],
  ['早上','zǎo shang','noun','buổi sáng','上午之前','早上六点起床。','Sáng sáu giờ dậy.',9,'日'],
  ['中午','zhōng wǔ','noun','buổi trưa','一天的中间','中午吃饭。','Trưa ăn cơm.',8,'丨'],
  ['下午','xià wǔ','noun','buổi chiều','中午之后','下午三点开会。','Chiều ba giờ họp.',7,'一'],
  ['晚上','wǎn shang','noun','buổi tối','天黑之后','晚上看电视。','Tối xem tivi.',14,'日'],
  ['点','diǎn','noun','giờ (đồng hồ)','表示时间','现在三点了。','Bây giờ ba giờ rồi.',9,'灬'],
  ['半','bàn','num','nửa, rưỡi','二分之一','三点半。','Ba giờ rưỡi.',5,'丨']),
  ...ZH('家庭',
  ['爸爸','bà ba','noun','bố, ba','父亲','爸爸在工作。','Bố đang làm việc.',16,'父'],
  ['妈妈','mā ma','noun','mẹ, má','母亲','妈妈做饭。','Mẹ nấu cơm.',12,'女'],
  ['哥哥','gē ge','noun','anh trai','年长的男兄弟','哥哥很高。','Anh trai rất cao.',20,'口'],
  ['姐姐','jiě jie','noun','chị gái','年长的女兄弟','姐姐上大学了。','Chị gái lên đại học rồi.',16,'女'],
  ['弟弟','dì di','noun','em trai','年幼的男兄弟','弟弟在上学。','Em trai đang đi học.',14,'弓'],
  ['妹妹','mèi mei','noun','em gái','年幼的女兄弟','妹妹很可爱。','Em gái rất dễ thương.',16,'女'],
  ['儿子','ér zi','noun','con trai','男孩子','我的儿子三岁。','Con trai tôi ba tuổi.',5,'儿'],
  ['女儿','nǚ ér','noun','con gái','女孩子','她的女儿很聪明。','Con gái cô ấy rất thông minh.',5,'女'],
  ['丈夫','zhàng fu','noun','chồng','妻子的配偶','她的丈夫是医生。','Chồng cô ấy là bác sĩ.',7,'一'],
  ['妻子','qī zi','noun','vợ','丈夫的配偶','他的妻子是老师。','Vợ anh ấy là giáo viên.',11,'女'],
  ['爷爷','yé ye','noun','ông nội','父亲的父亲','爷爷今年八十岁。','Ông nội năm nay tám mươi tuổi.',12,'父'],
  ['奶奶','nǎi nai','noun','bà nội','父亲的母亲','奶奶做的菜很好吃。','Bà nội nấu ăn rất ngon.',10,'女'],
  ['家','jiā','noun','nhà, gia đình','住的地方','我的家在北京。','Nhà tôi ở Bắc Kinh.',10,'宀'],
  ['家人','jiā rén','noun','người nhà','家庭成员','我爱我的家人。','Tôi yêu gia đình tôi.',12,'宀'],
  ['孩子','hái zi','noun','con, đứa trẻ','小孩','孩子们在玩。','Bọn trẻ đang chơi.',12,'子'],
  ['男人','nán rén','noun','đàn ông','成年男性','那个男人很高。','Người đàn ông đó rất cao.',9,'田'],
  ['女人','nǚ rén','noun','phụ nữ','成年女性','那个女人很漂亮。','Người phụ nữ đó rất xinh.',5,'女'],
  ['人','rén','noun','người','人类','这里有很多人。','Ở đây có rất nhiều người.',2,'人'],
  ['岁','suì','noun','tuổi','年龄单位','你几岁？','Bạn bao nhiêu tuổi?',6,'山'],
  ['大','dà','adj','to, lớn','体积大','这个房间很大。','Căn phòng này rất lớn.',3,'大'],
  ['小','xiǎo','adj','nhỏ, bé','体积小','小猫很可爱。','Mèo con rất dễ thương.',3,'小'],
  ['老','lǎo','adj','già','年纪大','老人在公园散步。','Người già đi dạo trong công viên.',6,'耂'],
  ['年轻','nián qīng','adj','trẻ','年纪小','她很年轻。','Cô ấy rất trẻ.',14,'干'],
  ['生日','shēng rì','noun','sinh nhật','出生的日子','生日快乐！','Chúc mừng sinh nhật!',9,'生'],
  ['爱','ài','verb','yêu','有感情','我爱你。','Tôi yêu bạn.',10,'爪'],
  ['喜欢','xǐ huān','verb','thích','有好感','我喜欢音乐。','Tôi thích âm nhạc.',19,'口'],
  ['男孩','nán hái','noun','con trai','小男性','那个男孩在跑步。','Cậu bé đó đang chạy.',14,'田'],
  ['女孩','nǚ hái','noun','con gái','小女性','女孩在唱歌。','Cô bé đang hát.',12,'女'],
  ['宝宝','bǎo bao','noun','em bé','小婴儿','宝宝在睡觉。','Em bé đang ngủ.',16,'宀'],
  ['结婚','jié hūn','verb','kết hôn','成为夫妻','他们去年结婚了。','Họ kết hôn năm ngoái.',20,'纟']),
  ...ZH('饮食',
  ['水','shuǐ','noun','nước','液体','请给我一杯水。','Cho tôi một cốc nước.',4,'水'],
  ['茶','chá','noun','trà','饮品','我喜欢喝茶。','Tôi thích uống trà.',9,'艹'],
  ['咖啡','kā fēi','noun','cà phê','饮品','我每天喝咖啡。','Tôi uống cà phê mỗi ngày.',19,'口'],
  ['牛奶','niú nǎi','noun','sữa bò','饮品','小孩要喝牛奶。','Trẻ em cần uống sữa.',9,'牛'],
  ['米饭','mǐ fàn','noun','cơm','主食','我们吃米饭。','Chúng tôi ăn cơm.',13,'米'],
  ['面条','miàn tiáo','noun','mì, phở','面食','我喜欢吃面条。','Tôi thích ăn mì.',16,'面'],
  ['鸡蛋','jī dàn','noun','trứng gà','食物','早上吃鸡蛋。','Sáng ăn trứng gà.',14,'鸟'],
  ['鸡肉','jī ròu','noun','thịt gà','肉类','这道鸡肉很好吃。','Món thịt gà này rất ngon.',13,'鸟'],
  ['鱼','yú','noun','cá','水中动物','我喜欢吃鱼。','Tôi thích ăn cá.',8,'鱼'],
  ['水果','shuǐ guǒ','noun','trái cây','植物果实','多吃水果好。','Ăn nhiều trái cây tốt.',12,'水'],
  ['苹果','píng guǒ','noun','quả táo','水果','这个苹果很甜。','Quả táo này rất ngọt.',16,'艹'],
  ['菜','cài','noun','rau, món ăn','蔬菜或菜肴','今天的菜很好吃。','Hôm nay món ăn rất ngon.',11,'艹'],
  ['肉','ròu','noun','thịt','动物的肉','我不太吃肉。','Tôi không ăn thịt lắm.',6,'肉'],
  ['面包','miàn bāo','noun','bánh mì','食物','早上吃面包。','Sáng ăn bánh mì.',14,'面'],
  ['糖','táng','noun','đường','甜味剂','少吃糖。','Ăn ít đường.',16,'米'],
  ['盐','yán','noun','muối','调味品','菜太咸了，盐多了。','Món ăn mặn quá, nhiều muối.',10,'皿'],
  ['吃','chī','verb','ăn','进食','你想吃什么？','Bạn muốn ăn gì?',6,'口'],
  ['喝','hē','verb','uống','饮用','我想喝水。','Tôi muốn uống nước.',12,'口'],
  ['饿','è','adj','đói','肚子空','我很饿。','Tôi rất đói.',10,'饣'],
  ['渴','kě','adj','khát','想喝水','我很渴。','Tôi rất khát.',12,'氵'],
  ['好吃','hǎo chī','adj','ngon','味道好','这个菜很好吃！','Món này rất ngon!',12,'女'],
  ['做饭','zuò fàn','verb','nấu cơm','烹饪','妈妈在做饭。','Mẹ đang nấu cơm.',18,'亻'],
  ['餐厅','cān tīng','noun','nhà hàng','吃饭的地方','我们去餐厅吃。','Chúng ta đi nhà hàng ăn.',21,'饣'],
  ['筷子','kuài zi','noun','đũa','吃饭的工具','用筷子吃饭。','Dùng đũa ăn cơm.',17,'竹'],
  ['碗','wǎn','noun','bát, chén','盛饭的器皿','给我一个碗。','Cho tôi một cái bát.',13,'石'],
  ['杯子','bēi zi','noun','cốc, ly','喝水的容器','这个杯子很漂亮。','Cái cốc này rất đẹp.',11,'木'],
  ['早饭','zǎo fàn','noun','bữa sáng','早上的饭','你吃早饭了吗？','Bạn ăn sáng chưa?',13,'日'],
  ['午饭','wǔ fàn','noun','bữa trưa','中午的饭','我们一起吃午饭。','Chúng ta cùng ăn trưa.',11,'十'],
  ['晚饭','wǎn fàn','noun','bữa tối','晚上的饭','晚饭吃什么？','Bữa tối ăn gì?',18,'日'],
  ['热','rè','adj','nóng (đồ ăn)','温度高','汤很热。','Canh rất nóng.',10,'灬']),
  ...ZH('颜色与形状',
  ['红','hóng','adj','đỏ','颜色','她穿红衣服。','Cô ấy mặc áo đỏ.',6,'纟'],
  ['蓝','lán','adj','xanh dương','颜色','天空是蓝色的。','Bầu trời màu xanh.',13,'艹'],
  ['绿','lǜ','adj','xanh lá','颜色','树叶是绿色的。','Lá cây màu xanh.',11,'纟'],
  ['黄','huáng','adj','vàng','颜色','香蕉是黄色的。','Chuối màu vàng.',11,'黄'],
  ['白','bái','adj','trắng','颜色','白色的云。','Mây trắng.',5,'白'],
  ['黑','hēi','adj','đen','颜色','他穿黑衣服。','Anh ấy mặc đồ đen.',12,'黑'],
  ['颜色','yán sè','noun','màu sắc','色彩','你喜欢什么颜色？','Bạn thích màu gì?',15,'页'],
  ['长','cháng','adj','dài','距离远','这条路很长。','Con đường này rất dài.',4,'长'],
  ['短','duǎn','adj','ngắn','距离近','她的头发很短。','Tóc cô ấy rất ngắn.',12,'矢'],
  ['高','gāo','adj','cao','身高或高度','他很高。','Anh ấy rất cao.',10,'亠'],
  ['低','dī','adj','thấp','不高','桌子很低。','Bàn rất thấp.',7,'亻'],
  ['圆','yuán','adj','tròn','形状','月亮是圆的。','Mặt trăng hình tròn.',13,'囗'],
  ['方','fāng','adj','vuông','形状','桌子是方的。','Bàn hình vuông.',4,'方'],
  ['新','xīn','adj','mới','刚出现的','我买了新衣服。','Tôi mua quần áo mới.',13,'斤'],
  ['旧','jiù','adj','cũ','不新的','这本旧书。','Quyển sách cũ này.',5,'丨'],
  ['多','duō','adj','nhiều','数量大','人很多。','Người rất nhiều.',6,'夕'],
  ['少','shǎo','adj','ít','数量小','人很少。','Người rất ít.',4,'小'],
  ['漂亮','piào liang','adj','xinh đẹp','好看','她很漂亮。','Cô ấy rất xinh.',25,'氵'],
  ['好看','hǎo kàn','adj','đẹp, hay','外表好','这本书很好看。','Quyển sách này rất hay.',15,'女'],
  ['胖','pàng','adj','béo, mập','体重大','我有点胖。','Tôi hơi mập.',9,'月'],
  ['瘦','shòu','adj','gầy, ốm','体重轻','她很瘦。','Cô ấy rất gầy.',14,'疒'],
  ['轻','qīng','adj','nhẹ','重量小','这个包很轻。','Cái túi này rất nhẹ.',9,'车'],
  ['重','zhòng','adj','nặng','重量大','这个箱子很重。','Cái hòm này rất nặng.',9,'里'],
  ['快','kuài','adj','nhanh','速度高','他跑得很快。','Anh ấy chạy rất nhanh.',7,'忄'],
  ['慢','màn','adj','chậm','速度低','请说慢一点。','Xin nói chậm hơn.',14,'忄'],
  ['厚','hòu','adj','dày','有厚度','这本书很厚。','Quyển sách này rất dày.',9,'厂'],
  ['薄','báo','adj','mỏng','不厚','纸很薄。','Giấy rất mỏng.',16,'艹'],
  ['深','shēn','adj','sâu','深度大','水很深。','Nước rất sâu.',11,'氵'],
  ['浅','qiǎn','adj','nông, nhạt','深度小','水很浅。','Nước rất nông.',8,'氵'],
  ['亮','liàng','adj','sáng','有光','灯很亮。','Đèn rất sáng.',9,'亠']),
];
