// WordSpark A1 Seed Data — 300 words, 10 topics
// Format: [word, ipa, pos, vi, en, ex_en, ex_vi]
import { WORDS_PART2 } from './seed-data-p2.js';
import { WORDS_A2 } from './seed-data-a2.js';
import { WORDS_INDUSTRY } from './seed-data-industry.js';
import { WORDS_INDUSTRY2 } from './seed-data-industry2.js';
import { WORDS_ZH } from './seed-data-zh.js';
import { WORDS_ZH2 } from './seed-data-zh2.js';
export const TOPICS = [
  // A1 English Topics
  {name:'Greetings',name_vi:'Chào hỏi',icon:'👋',count:30,lang:'en'},
  {name:'Numbers & Time',name_vi:'Số & Thời gian',icon:'🔢',count:30,lang:'en'},
  {name:'Family',name_vi:'Gia đình',icon:'👨‍👩‍👧‍👦',count:30,lang:'en'},
  {name:'Food & Drink',name_vi:'Đồ ăn & Thức uống',icon:'🍔',count:30,lang:'en'},
  {name:'Colors & Shapes',name_vi:'Màu sắc & Hình dạng',icon:'🎨',count:30,lang:'en'},
  {name:'Daily Activities',name_vi:'Sinh hoạt hàng ngày',icon:'🏃',count:30,lang:'en'},
  {name:'Weather',name_vi:'Thời tiết',icon:'☀️',count:30,lang:'en'},
  {name:'Travel',name_vi:'Du lịch',icon:'✈️',count:30,lang:'en'},
  {name:'Shopping',name_vi:'Mua sắm',icon:'🛒',count:30,lang:'en'},
  {name:'Body & Health',name_vi:'Cơ thể & Sức khỏe',icon:'💪',count:30,lang:'en'},
  // A2 Topics
  {name:'Emotions & Feelings',name_vi:'Cảm xúc',icon:'💖',count:30,level:'A2',lang:'en'},
  {name:'School & Education',name_vi:'Trường học',icon:'🎒',count:30,level:'A2',lang:'en'},
  {name:'Work & Jobs',name_vi:'Công việc',icon:'💼',count:30,level:'A2',lang:'en'},
  {name:'House & Home',name_vi:'Nhà cửa',icon:'🏠',count:30,level:'A2',lang:'en'},
  {name:'Technology',name_vi:'Công nghệ',icon:'💻',count:30,level:'A2',lang:'en'},
  // A2 Industry Topics
  {name:'Business & Finance',name_vi:'Kinh doanh',icon:'💰',count:30,level:'A2',lang:'en'},
  {name:'IT & Software',name_vi:'Công nghệ TT',icon:'🖥️',count:30,level:'A2',lang:'en'},
  {name:'Medical & Healthcare',name_vi:'Y tế',icon:'🏥',count:30,level:'A2',lang:'en'},
  {name:'Restaurant & Hospitality',name_vi:'Nhà hàng',icon:'🍽️',count:30,level:'A2',lang:'en'},
  {name:'Marketing & Sales',name_vi:'Tiếp thị',icon:'📢',count:30,level:'A2',lang:'en'},
  // B1 Industry Topics
  {name:'Law & Legal',name_vi:'Luật pháp',icon:'⚖️',count:30,level:'B1',lang:'en'},
  {name:'Construction',name_vi:'Xây dựng',icon:'🏗️',count:30,level:'B1',lang:'en'},
  {name:'Education & Training',name_vi:'Đào tạo',icon:'📝',count:30,level:'B1',lang:'en'},
  {name:'Sports & Fitness',name_vi:'Thể thao',icon:'⚽',count:30,level:'B1',lang:'en'},
  {name:'Arts & Entertainment',name_vi:'Nghệ thuật',icon:'🎬',count:30,level:'B1',lang:'en'},
  // Chinese HSK1 Topics
  {name:'问候',name_vi:'Chào hỏi',icon:'👋',count:30,lang:'zh'},
  {name:'数字与时间',name_vi:'Số & Thời gian',icon:'🔢',count:30,lang:'zh'},
  {name:'家庭',name_vi:'Gia đình',icon:'👨‍👩‍👧‍👦',count:30,lang:'zh'},
  {name:'饮食',name_vi:'Đồ ăn & Thức uống',icon:'🍔',count:30,lang:'zh'},
  {name:'颜色与形状',name_vi:'Màu sắc & Hình dạng',icon:'🎨',count:30,lang:'zh'},
  {name:'日常活动',name_vi:'Sinh hoạt hàng ngày',icon:'🏃',count:30,lang:'zh'},
  {name:'天气',name_vi:'Thời tiết',icon:'☀️',count:30,lang:'zh'},
  {name:'旅行',name_vi:'Du lịch',icon:'✈️',count:30,lang:'zh'},
  {name:'购物',name_vi:'Mua sắm',icon:'🛒',count:30,lang:'zh'},
  {name:'身体与健康',name_vi:'Cơ thể & Sức khỏe',icon:'💪',count:30,lang:'zh'},
];

const W = (t,...d) => d.map(r=>({word:r[0],ipa:r[1],pos:r[2],vi:r[3],en:r[4],ex_en:r[5],ex_vi:r[6],topic:t,level:'A1',lang:'en'}));

export const WORDS = [
  // Greetings
  ...W('Greetings',
  ['hello','/həˈloʊ/','intj','xin chào','a greeting','Hello, how are you?','Xin chào, bạn khỏe không?'],
  ['goodbye','/ɡʊdˈbaɪ/','intj','tạm biệt','farewell','Goodbye, see you!','Tạm biệt, hẹn gặp lại!'],
  ['good morning','/ɡʊd ˈmɔːrnɪŋ/','intj','chào buổi sáng','morning greeting','Good morning, everyone!','Chào buổi sáng mọi người!'],
  ['good afternoon','/ɡʊd ˌæf.tɚˈnuːn/','intj','chào buổi chiều','afternoon greeting','Good afternoon, sir.','Chào buổi chiều, thưa ông.'],
  ['good evening','/ɡʊd ˈiːv.nɪŋ/','intj','chào buổi tối','evening greeting','Good evening, welcome!','Chào buổi tối, chào mừng!'],
  ['good night','/ɡʊd naɪt/','intj','chúc ngủ ngon','night farewell','Good night, sweet dreams!','Chúc ngủ ngon, mơ đẹp!'],
  ['thank you','/θæŋk juː/','intj','cảm ơn','gratitude','Thank you very much!','Cảm ơn rất nhiều!'],
  ['please','/pliːz/','adv','làm ơn','polite request','Please sit down.','Làm ơn ngồi xuống.'],
  ['sorry','/ˈsɑːri/','adj','xin lỗi','feeling regret','I am sorry for being late.','Tôi xin lỗi vì đến muộn.'],
  ['excuse me','/ɪkˈskjuːz miː/','intj','xin phép','polite interruption','Excuse me, where is the station?','Xin phép, ga tàu ở đâu?'],
  ['yes','/jes/','adv','vâng, có','affirmative','Yes, I understand.','Vâng, tôi hiểu.'],
  ['no','/noʊ/','adv','không','negative','No, thank you.','Không, cảm ơn.'],
  ['welcome','/ˈwel.kəm/','intj','chào mừng','arrival greeting','Welcome to our school!','Chào mừng đến trường!'],
  ['how are you','/haʊ ɑːr juː/','intj','bạn khỏe không','asking well-being','How are you today?','Hôm nay bạn khỏe không?'],
  ['fine','/faɪn/','adj','khỏe, tốt','in good condition','I am fine, thanks.','Tôi khỏe, cảm ơn.'],
  ['nice to meet you','/naɪs tə miːt juː/','intj','rất vui được gặp bạn','first meeting','Nice to meet you!','Rất vui được gặp bạn!'],
  ['see you later','/siː juː ˈleɪ.tɚ/','intj','hẹn gặp lại','casual farewell','See you later, bye!','Hẹn gặp lại, tạm biệt!'],
  ['name','/neɪm/','noun','tên','what someone is called','My name is Anna.','Tên tôi là Anna.'],
  ['friend','/frend/','noun','bạn bè','a person you like','She is my best friend.','Cô ấy là bạn thân nhất.'],
  ['help','/help/','verb','giúp đỡ','to assist','Can you help me?','Bạn có thể giúp tôi không?'],
  ['understand','/ˌʌn.dɚˈstænd/','verb','hiểu','to comprehend','I do not understand.','Tôi không hiểu.'],
  ['speak','/spiːk/','verb','nói','to talk','Do you speak English?','Bạn có nói tiếng Anh không?'],
  ['repeat','/rɪˈpiːt/','verb','nhắc lại','to say again','Can you repeat that?','Bạn có thể nhắc lại không?'],
  ['know','/noʊ/','verb','biết','to be aware of','I do not know.','Tôi không biết.'],
  ['come','/kʌm/','verb','đến','to move toward','Come here, please.','Đến đây, làm ơn.'],
  ['go','/ɡoʊ/','verb','đi','to move away','Let us go to the park.','Chúng ta đi công viên đi.'],
  ['happy','/ˈhæp.i/','adj','vui vẻ','feeling joy','I am very happy today!','Hôm nay tôi rất vui!'],
  ['nice','/naɪs/','adj','tốt đẹp','pleasant','That is very nice of you.','Bạn thật tốt bụng.'],
  ['thanks','/θæŋks/','intj','cảm ơn','informal gratitude','Thanks a lot!','Cảm ơn nhiều!'],
  ['bye','/baɪ/','intj','tạm biệt','informal farewell','Bye! Take care!','Tạm biệt! Bảo trọng!']),
  // Numbers & Time
  ...W('Numbers & Time',
  ['one','/wʌn/','noun','một','the number 1','I have one cat.','Tôi có một con mèo.'],
  ['two','/tuː/','noun','hai','the number 2','She has two brothers.','Cô ấy có hai anh trai.'],
  ['three','/θriː/','noun','ba','the number 3','There are three books.','Có ba quyển sách.'],
  ['four','/fɔːr/','noun','bốn','the number 4','I need four eggs.','Tôi cần bốn quả trứng.'],
  ['five','/faɪv/','noun','năm','the number 5','He is five years old.','Cậu bé năm tuổi.'],
  ['ten','/ten/','noun','mười','the number 10','I count to ten.','Tôi đếm đến mười.'],
  ['twenty','/ˈtwen.t̬i/','noun','hai mươi','the number 20','She is twenty years old.','Cô ấy hai mươi tuổi.'],
  ['hundred','/ˈhʌn.drəd/','noun','một trăm','the number 100','There are a hundred students.','Có một trăm học sinh.'],
  ['zero','/ˈzɪr.oʊ/','noun','số không','the number 0','The temperature is zero.','Nhiệt độ là số không.'],
  ['first','/fɜːrst/','adj','thứ nhất','before all others','This is my first day.','Đây là ngày đầu tiên.'],
  ['time','/taɪm/','noun','thời gian','ongoing progression','What time is it?','Mấy giờ rồi?'],
  ['hour','/aʊr/','noun','giờ','60 minutes','I wait for one hour.','Tôi đợi một tiếng.'],
  ['minute','/ˈmɪn.ɪt/','noun','phút','60 seconds','Wait a minute, please.','Đợi một phút.'],
  ['second','/ˈsek.ənd/','noun','giây','a unit of time','Just a second!','Chỉ một giây!'],
  ['today','/təˈdeɪ/','adv','hôm nay','this present day','Today is Monday.','Hôm nay là thứ Hai.'],
  ['tomorrow','/təˈmɑːr.oʊ/','adv','ngày mai','day after today','See you tomorrow!','Gặp bạn ngày mai!'],
  ['yesterday','/ˈjes.tɚ.deɪ/','adv','hôm qua','day before today','Yesterday was sunny.','Hôm qua trời nắng.'],
  ['week','/wiːk/','noun','tuần','seven days','I work five days a week.','Tôi làm việc năm ngày một tuần.'],
  ['month','/mʌnθ/','noun','tháng','about 30 days','This month is July.','Tháng này là tháng Bảy.'],
  ['year','/jɪr/','noun','năm','12 months','Happy New Year!','Chúc mừng năm mới!'],
  ['morning','/ˈmɔːr.nɪŋ/','noun','buổi sáng','early part of day','I run every morning.','Tôi chạy bộ mỗi sáng.'],
  ['afternoon','/ˌæf.tɚˈnuːn/','noun','buổi chiều','middle part of day','I study in the afternoon.','Tôi học vào buổi chiều.'],
  ['evening','/ˈiːv.nɪŋ/','noun','buổi tối','late part of day','We eat in the evening.','Chúng tôi ăn vào buổi tối.'],
  ['night','/naɪt/','noun','đêm','dark hours','Stars shine at night.','Sao lấp lánh ban đêm.'],
  ['Monday','/ˈmʌn.deɪ/','noun','thứ Hai','first weekday','I start work on Monday.','Tôi bắt đầu làm thứ Hai.'],
  ['clock','/klɑːk/','noun','đồng hồ','time device','Look at the clock.','Nhìn đồng hồ đi.'],
  ['early','/ˈɝː.li/','adv','sớm','before expected time','I wake up early.','Tôi thức dậy sớm.'],
  ['late','/leɪt/','adj','muộn, trễ','after expected time','Do not be late!','Đừng đến trễ!'],
  ['now','/naʊ/','adv','bây giờ','at this moment','I am busy now.','Bây giờ tôi đang bận.'],
  ['always','/ˈɔːl.weɪz/','adv','luôn luôn','at all times','She always smiles.','Cô ấy luôn mỉm cười.']),
  // Family
  ...W('Family',
  ['family','/ˈfæm.əl.i/','noun','gia đình','a group of relatives','I love my family.','Tôi yêu gia đình.'],
  ['mother','/ˈmʌð.ɚ/','noun','mẹ','female parent','My mother cooks well.','Mẹ tôi nấu ăn giỏi.'],
  ['father','/ˈfɑː.ðɚ/','noun','bố','male parent','My father is a teacher.','Bố tôi là giáo viên.'],
  ['sister','/ˈsɪs.tɚ/','noun','chị/em gái','female sibling','My sister is older.','Chị tôi lớn hơn tôi.'],
  ['brother','/ˈbrʌð.ɚ/','noun','anh/em trai','male sibling','I have two brothers.','Tôi có hai anh trai.'],
  ['son','/sʌn/','noun','con trai','male child','Their son is six.','Con trai họ sáu tuổi.'],
  ['daughter','/ˈdɑː.t̬ɚ/','noun','con gái','female child','My daughter likes drawing.','Con gái tôi thích vẽ.'],
  ['husband','/ˈhʌz.bənd/','noun','chồng','married man','Her husband is a doctor.','Chồng cô ấy là bác sĩ.'],
  ['wife','/waɪf/','noun','vợ','married woman','His wife is very kind.','Vợ anh ấy rất tốt bụng.'],
  ['baby','/ˈbeɪ.bi/','noun','em bé','very young child','The baby is sleeping.','Em bé đang ngủ.'],
  ['child','/tʃaɪld/','noun','trẻ em','young person','Every child needs love.','Mỗi đứa trẻ cần tình yêu.'],
  ['parent','/ˈper.ənt/','noun','cha mẹ','mother or father','My parents live in Hanoi.','Bố mẹ tôi sống ở Hà Nội.'],
  ['grandmother','/ˈɡræn.mʌð.ɚ/','noun','bà','parent\'s mother','My grandmother is 80.','Bà tôi 80 tuổi.'],
  ['grandfather','/ˈɡræn.fɑː.ðɚ/','noun','ông','parent\'s father','Grandfather tells stories.','Ông kể chuyện.'],
  ['uncle','/ˈʌŋ.kəl/','noun','chú/bác/cậu','parent\'s brother','My uncle lives in the city.','Chú tôi sống ở thành phố.'],
  ['aunt','/ænt/','noun','cô/dì/mợ','parent\'s sister','Aunt Mai is a nurse.','Cô Mai là y tá.'],
  ['cousin','/ˈkʌz.ən/','noun','anh chị em họ','uncle\'s child','My cousin visits on weekends.','Anh họ tôi ghé cuối tuần.'],
  ['love','/lʌv/','verb','yêu','feel deep affection','I love you, Mom!','Con yêu mẹ!'],
  ['home','/hoʊm/','noun','nhà','where one lives','I am going home.','Tôi đang về nhà.'],
  ['house','/haʊs/','noun','ngôi nhà','a building to live in','Our house is big.','Nhà chúng tôi rộng.'],
  ['man','/mæn/','noun','đàn ông','adult male','That man is my neighbor.','Người đó là hàng xóm tôi.'],
  ['woman','/ˈwʊm.ən/','noun','phụ nữ','adult female','The woman is smiling.','Người phụ nữ đang cười.'],
  ['boy','/bɔɪ/','noun','con trai nhỏ','young male','The boy plays soccer.','Cậu bé chơi đá bóng.'],
  ['girl','/ɡɜːrl/','noun','con gái nhỏ','young female','The girl reads a book.','Cô bé đọc sách.'],
  ['people','/ˈpiː.pəl/','noun','mọi người','human beings','Many people like music.','Nhiều người thích nhạc.'],
  ['old','/oʊld/','adj','già, cũ','not young or new','My grandfather is old.','Ông tôi đã già.'],
  ['young','/jʌŋ/','adj','trẻ','not old','She is very young.','Cô ấy rất trẻ.'],
  ['birthday','/ˈbɜːrθ.deɪ/','noun','sinh nhật','anniversary of birth','Happy birthday!','Chúc mừng sinh nhật!'],
  ['together','/təˈɡeð.ɚ/','adv','cùng nhau','with each other','We eat together.','Chúng tôi ăn cùng nhau.'],
  ['pet','/pet/','noun','thú cưng','a domestic animal','Do you have a pet?','Bạn có nuôi thú cưng không?']),
  // Food & Drink
  ...W('Food & Drink',
  ['water','/ˈwɑː.t̬ɚ/','noun','nước','a clear liquid','I drink a lot of water.','Tôi uống nhiều nước.'],
  ['food','/fuːd/','noun','thức ăn','things you eat','The food is delicious.','Thức ăn rất ngon.'],
  ['rice','/raɪs/','noun','cơm, gạo','a cereal grain','I eat rice every day.','Tôi ăn cơm mỗi ngày.'],
  ['bread','/bred/','noun','bánh mì','baked flour food','I have bread for breakfast.','Tôi ăn bánh mì sáng.'],
  ['egg','/eɡ/','noun','trứng','oval food from hens','I want two eggs.','Tôi muốn hai quả trứng.'],
  ['chicken','/ˈtʃɪk.ɪn/','noun','thịt gà','poultry meat','I like fried chicken.','Tôi thích gà rán.'],
  ['fish','/fɪʃ/','noun','cá','aquatic animal','This fish is very fresh.','Con cá này rất tươi.'],
  ['meat','/miːt/','noun','thịt','animal flesh as food','Do you eat meat?','Bạn có ăn thịt không?'],
  ['fruit','/fruːt/','noun','trái cây','sweet plant product','Eat more fruit!','Ăn nhiều trái cây hơn!'],
  ['apple','/ˈæp.əl/','noun','táo','a round red fruit','An apple a day is good.','Mỗi ngày một quả táo tốt.'],
  ['banana','/bəˈnæn.ə/','noun','chuối','a long yellow fruit','I eat a banana daily.','Tôi ăn chuối mỗi ngày.'],
  ['vegetable','/ˈvedʒ.tə.bəl/','noun','rau','edible plant','Vegetables are healthy.','Rau rất tốt cho sức khỏe.'],
  ['milk','/mɪlk/','noun','sữa','white liquid from cows','Children drink milk.','Trẻ em uống sữa.'],
  ['coffee','/ˈkɑː.fi/','noun','cà phê','a hot brown drink','I need coffee every morning.','Tôi cần cà phê mỗi sáng.'],
  ['tea','/tiː/','noun','trà','a hot leaf drink','Would you like some tea?','Bạn muốn uống trà không?'],
  ['juice','/dʒuːs/','noun','nước ép','liquid from fruit','Orange juice is refreshing.','Nước cam rất mát.'],
  ['sugar','/ˈʃʊɡ.ɚ/','noun','đường','sweet substance','No sugar for me, please.','Không đường cho tôi.'],
  ['salt','/sɑːlt/','noun','muối','white seasoning','Add a little salt.','Thêm một chút muối.'],
  ['soup','/suːp/','noun','canh, súp','liquid food','This soup is very hot.','Canh này rất nóng.'],
  ['cake','/keɪk/','noun','bánh ngọt','sweet baked food','I made a birthday cake.','Tôi làm bánh sinh nhật.'],
  ['eat','/iːt/','verb','ăn','to consume food','I eat breakfast at seven.','Tôi ăn sáng lúc bảy giờ.'],
  ['drink','/drɪŋk/','verb','uống','to consume liquid','Drink more water.','Uống nhiều nước hơn.'],
  ['cook','/kʊk/','verb','nấu ăn','to prepare food','My mom cooks every day.','Mẹ tôi nấu ăn mỗi ngày.'],
  ['hungry','/ˈhʌŋ.ɡri/','adj','đói','wanting food','I am very hungry.','Tôi rất đói.'],
  ['thirsty','/ˈθɜːr.sti/','adj','khát','wanting drink','Are you thirsty?','Bạn có khát không?'],
  ['delicious','/dɪˈlɪʃ.əs/','adj','ngon','very tasty','This cake is delicious!','Bánh này ngon quá!'],
  ['breakfast','/ˈbrek.fəst/','noun','bữa sáng','morning meal','Breakfast is ready.','Bữa sáng đã sẵn sàng.'],
  ['lunch','/lʌntʃ/','noun','bữa trưa','midday meal','What is for lunch?','Bữa trưa ăn gì?'],
  ['dinner','/ˈdɪn.ɚ/','noun','bữa tối','evening meal','Dinner is at seven.','Bữa tối lúc bảy giờ.'],
  ['restaurant','/ˈres.tə.rɑːnt/','noun','nhà hàng','place to eat out','Let us go to a restaurant.','Chúng ta đi nhà hàng đi.']),
  // Colors & Shapes
  ...W('Colors & Shapes',
  ['red','/red/','adj','đỏ','the color of blood','The apple is red.','Quả táo màu đỏ.'],
  ['blue','/bluː/','adj','xanh dương','the color of sky','The sky is blue.','Bầu trời màu xanh.'],
  ['green','/ɡriːn/','adj','xanh lá','the color of grass','The tree is green.','Cái cây màu xanh lá.'],
  ['yellow','/ˈjel.oʊ/','adj','vàng','the color of sun','The banana is yellow.','Quả chuối màu vàng.'],
  ['white','/waɪt/','adj','trắng','the lightest color','The snow is white.','Tuyết màu trắng.'],
  ['black','/blæk/','adj','đen','the darkest color','I wear a black shirt.','Tôi mặc áo đen.'],
  ['orange','/ˈɔːr.ɪndʒ/','adj','cam','warm reddish-yellow','The sunset is orange.','Hoàng hôn màu cam.'],
  ['pink','/pɪŋk/','adj','hồng','a pale red color','She likes pink flowers.','Cô ấy thích hoa hồng.'],
  ['purple','/ˈpɜːr.pəl/','adj','tím','mix of red and blue','The dress is purple.','Cái váy màu tím.'],
  ['brown','/braʊn/','adj','nâu','the color of earth','The dog is brown.','Con chó màu nâu.'],
  ['gray','/ɡreɪ/','adj','xám','between black and white','The sky is gray today.','Hôm nay trời xám.'],
  ['gold','/ɡoʊld/','adj','vàng kim','shiny yellow color','She wears a gold ring.','Cô ấy đeo nhẫn vàng.'],
  ['silver','/ˈsɪl.vɚ/','adj','bạc','shiny gray color','The car is silver.','Chiếc xe màu bạc.'],
  ['color','/ˈkʌl.ɚ/','noun','màu sắc','visual property','What color do you like?','Bạn thích màu gì?'],
  ['bright','/braɪt/','adj','sáng, tươi','giving out light','The room is very bright.','Căn phòng rất sáng.'],
  ['dark','/dɑːrk/','adj','tối','without light','It is dark outside.','Bên ngoài tối rồi.'],
  ['light','/laɪt/','adj','nhạt, sáng','not dark','I like light blue.','Tôi thích xanh nhạt.'],
  ['circle','/ˈsɜːr.kəl/','noun','hình tròn','a round shape','Draw a circle.','Vẽ một hình tròn.'],
  ['square','/skwer/','noun','hình vuông','4 equal sides','The box is a square.','Cái hộp hình vuông.'],
  ['triangle','/ˈtraɪ.æŋ.ɡəl/','noun','hình tam giác','a 3-sided shape','A triangle has three sides.','Tam giác có ba cạnh.'],
  ['star','/stɑːr/','noun','ngôi sao','a pointed shape','I can see many stars.','Tôi thấy nhiều ngôi sao.'],
  ['heart','/hɑːrt/','noun','trái tim','a love symbol','She drew a heart.','Cô ấy vẽ trái tim.'],
  ['line','/laɪn/','noun','đường thẳng','a long thin mark','Draw a straight line.','Vẽ một đường thẳng.'],
  ['big','/bɪɡ/','adj','to, lớn','of great size','The elephant is big.','Con voi rất to.'],
  ['small','/smɑːl/','adj','nhỏ','not large','The cat is small.','Con mèo nhỏ.'],
  ['long','/lɑːŋ/','adj','dài','of great length','The river is very long.','Con sông rất dài.'],
  ['short','/ʃɔːrt/','adj','ngắn, thấp','not long or tall','She has short hair.','Cô ấy có tóc ngắn.'],
  ['round','/raʊnd/','adj','tròn','shaped like a circle','The ball is round.','Quả bóng hình tròn.'],
  ['beautiful','/ˈbjuː.t̬ə.fəl/','adj','đẹp','very attractive','The flower is beautiful.','Bông hoa rất đẹp.'],
  ['new','/nuː/','adj','mới','recently made','I have a new phone.','Tôi có điện thoại mới.']),
].concat(WORDS_PART2).concat(WORDS_A2).concat(WORDS_INDUSTRY).concat(WORDS_INDUSTRY2).concat(WORDS_ZH).concat(WORDS_ZH2);
